import React from 'react'
import {Composition} from 'remotion'
import {
  V01aFirstSiteTerminal,
  V01bFirstSiteBrowser,
  V01cFirstSiteEditor,
  V02aSkillInstall,
  V02bBeforeAfterDesign,
  V02cSkillFileEditor,
  V03aLocalhostVsDeployed,
  V03bHereNowPublish,
  V03cLiveSiteShare,
  V04aGitTimelineBranch,
  V04bGitInitCommit,
  V04cLocalToGitHubCloud,
  V05aRawXmlToCards,
  V05bFeedPullTerminal,
  V05cAutoUpdatingFeed,
  V06aSpreadsheetToSupabase,
  V06bSupabaseDashboard,
  V06cFrontendApiBackend,
  V07aAuthFormToLoggedIn,
  V07bSessionCookieConcept,
  V07cRLSConcept,
  V08aGuestbookBrowser,
  V08bVercelDeployTerminal,
  V08cStackConcept,
  V09aWorkflowConcept,
  V09bTriggerSetupTerminal,
  V09cTriggerDashboard,
  V10aLaptopVsServerConcept,
  V10bSshTerminal,
  V10cTailscaleNetworkConcept,
  V11aDeploymentDecisionTree,
  V11bVercelProdTerminal,
  V11cEnvSecurityEditor,
  V12aFirstAgentEditor,
  V12bAgentConceptDiagram,
  V12cPiAgentTerminal,
  V13aToolsConceptDiagram,
  V13bInstallToolsTerminal,
  V13cSkillsMarketplaceBrowser,
  V14aAgentPocketConcept,
  V14bHeartbeatTerminal,
  V14cTelegramChatBrowser,
  V15aBuildLoopConcept,
  V15bDogfoodDebugTerminal,
  V15cSpecProgressEditor,
  V16aGmailCliTerminal,
  V16bCustomEmailBrowser,
  V16cEmailDataFlowConcept,
  V17aTodoMarkdownEditor,
  V17bTodoAppBrowser,
  V17cFileToAppConcept,
  V18aOpsDashboardBrowser,
  V18bDashboardSourcesConcept,
  V18cBuildDashboardTerminal,
  V19aPipelineConcept,
  V19bContentEngineBrowser,
  V19cPipelineRunTerminal,
  V20aBadVsGoodPromptTerminal,
  V20bSimplerTermsTerminal,
  V20cPromptFlowConcept,
  V21aInspectConsoleBrowser,
  V21bPasteErrorsTerminal,
  V21cDebugLoopConcept,
  V22aWorkspaceTreeEditor,
  V22bAgentsHierarchyConcept,
  V22cSubscriptionStackConcept,
} from './scenes/cookbooks'

const FPS = 30
const WIDTH = 1920
const HEIGHT = 1080

const cookbookCompositions = [
  {id: 'Cookbook-01a', component: V01aFirstSiteTerminal, durationInFrames: 510},
  {id: 'Cookbook-01b', component: V01bFirstSiteBrowser, durationInFrames: 510},
  {id: 'Cookbook-01c', component: V01cFirstSiteEditor, durationInFrames: 510},
  {id: 'Cookbook-02a', component: V02aSkillInstall, durationInFrames: 510},
  {id: 'Cookbook-02b', component: V02bBeforeAfterDesign, durationInFrames: 510},
  {id: 'Cookbook-02c', component: V02cSkillFileEditor, durationInFrames: 510},
  {id: 'Cookbook-03a', component: V03aLocalhostVsDeployed, durationInFrames: 510},
  {id: 'Cookbook-03b', component: V03bHereNowPublish, durationInFrames: 510},
  {id: 'Cookbook-03c', component: V03cLiveSiteShare, durationInFrames: 510},
  {id: 'Cookbook-04a', component: V04aGitTimelineBranch, durationInFrames: 510},
  {id: 'Cookbook-04b', component: V04bGitInitCommit, durationInFrames: 510},
  {id: 'Cookbook-04c', component: V04cLocalToGitHubCloud, durationInFrames: 510},
  {id: 'Cookbook-05a', component: V05aRawXmlToCards, durationInFrames: 510},
  {id: 'Cookbook-05b', component: V05bFeedPullTerminal, durationInFrames: 510},
  {id: 'Cookbook-05c', component: V05cAutoUpdatingFeed, durationInFrames: 510},
  {id: 'Cookbook-06a', component: V06aSpreadsheetToSupabase, durationInFrames: 510},
  {id: 'Cookbook-06b', component: V06bSupabaseDashboard, durationInFrames: 510},
  {id: 'Cookbook-06c', component: V06cFrontendApiBackend, durationInFrames: 510},
  {id: 'Cookbook-07a', component: V07aAuthFormToLoggedIn, durationInFrames: 510},
  {id: 'Cookbook-07b', component: V07bSessionCookieConcept, durationInFrames: 510},
  {id: 'Cookbook-07c', component: V07cRLSConcept, durationInFrames: 510},
  {id: 'Cookbook-08a', component: V08aGuestbookBrowser, durationInFrames: 510},
  {id: 'Cookbook-08b', component: V08bVercelDeployTerminal, durationInFrames: 510},
  {id: 'Cookbook-08c', component: V08cStackConcept, durationInFrames: 510},
  {id: 'Cookbook-09a', component: V09aWorkflowConcept, durationInFrames: 510},
  {id: 'Cookbook-09b', component: V09bTriggerSetupTerminal, durationInFrames: 510},
  {id: 'Cookbook-09c', component: V09cTriggerDashboard, durationInFrames: 510},
  {id: 'Cookbook-10a', component: V10aLaptopVsServerConcept, durationInFrames: 510},
  {id: 'Cookbook-10b', component: V10bSshTerminal, durationInFrames: 510},
  {id: 'Cookbook-10c', component: V10cTailscaleNetworkConcept, durationInFrames: 510},
  {id: 'Cookbook-11a', component: V11aDeploymentDecisionTree, durationInFrames: 510},
  {id: 'Cookbook-11b', component: V11bVercelProdTerminal, durationInFrames: 510},
  {id: 'Cookbook-11c', component: V11cEnvSecurityEditor, durationInFrames: 510},
  {id: 'Cookbook-12a', component: V12aFirstAgentEditor, durationInFrames: 510},
  {id: 'Cookbook-12b', component: V12bAgentConceptDiagram, durationInFrames: 510},
  {id: 'Cookbook-12c', component: V12cPiAgentTerminal, durationInFrames: 510},
  {id: 'Cookbook-13a', component: V13aToolsConceptDiagram, durationInFrames: 510},
  {id: 'Cookbook-13b', component: V13bInstallToolsTerminal, durationInFrames: 510},
  {id: 'Cookbook-13c', component: V13cSkillsMarketplaceBrowser, durationInFrames: 510},
  {id: 'Cookbook-14a', component: V14aAgentPocketConcept, durationInFrames: 510},
  {id: 'Cookbook-14b', component: V14bHeartbeatTerminal, durationInFrames: 510},
  {id: 'Cookbook-14c', component: V14cTelegramChatBrowser, durationInFrames: 510},
  {id: 'Cookbook-15a', component: V15aBuildLoopConcept, durationInFrames: 510},
  {id: 'Cookbook-15b', component: V15bDogfoodDebugTerminal, durationInFrames: 510},
  {id: 'Cookbook-15c', component: V15cSpecProgressEditor, durationInFrames: 510},
  {id: 'Cookbook-16a', component: V16aGmailCliTerminal, durationInFrames: 510},
  {id: 'Cookbook-16b', component: V16bCustomEmailBrowser, durationInFrames: 510},
  {id: 'Cookbook-16c', component: V16cEmailDataFlowConcept, durationInFrames: 510},
  {id: 'Cookbook-17a', component: V17aTodoMarkdownEditor, durationInFrames: 510},
  {id: 'Cookbook-17b', component: V17bTodoAppBrowser, durationInFrames: 510},
  {id: 'Cookbook-17c', component: V17cFileToAppConcept, durationInFrames: 510},
  {id: 'Cookbook-18a', component: V18aOpsDashboardBrowser, durationInFrames: 510},
  {id: 'Cookbook-18b', component: V18bDashboardSourcesConcept, durationInFrames: 510},
  {id: 'Cookbook-18c', component: V18cBuildDashboardTerminal, durationInFrames: 510},
  {id: 'Cookbook-19a', component: V19aPipelineConcept, durationInFrames: 510},
  {id: 'Cookbook-19b', component: V19bContentEngineBrowser, durationInFrames: 510},
  {id: 'Cookbook-19c', component: V19cPipelineRunTerminal, durationInFrames: 510},
  {id: 'Cookbook-20a', component: V20aBadVsGoodPromptTerminal, durationInFrames: 510},
  {id: 'Cookbook-20b', component: V20bSimplerTermsTerminal, durationInFrames: 510},
  {id: 'Cookbook-20c', component: V20cPromptFlowConcept, durationInFrames: 510},
  {id: 'Cookbook-21a', component: V21aInspectConsoleBrowser, durationInFrames: 510},
  {id: 'Cookbook-21b', component: V21bPasteErrorsTerminal, durationInFrames: 510},
  {id: 'Cookbook-21c', component: V21cDebugLoopConcept, durationInFrames: 510},
  {id: 'Cookbook-22a', component: V22aWorkspaceTreeEditor, durationInFrames: 510},
  {id: 'Cookbook-22b', component: V22bAgentsHierarchyConcept, durationInFrames: 510},
  {id: 'Cookbook-22c', component: V22cSubscriptionStackConcept, durationInFrames: 510},
]

export const CookbookCompositions: React.FC = () => {
  return (
    <>
      {cookbookCompositions.map(({id, component, durationInFrames}) => (
        <Composition
          key={id}
          id={id}
          component={component}
          durationInFrames={durationInFrames}
          fps={FPS}
          width={WIDTH}
          height={HEIGHT}
        />
      ))}
    </>
  )
}
